### PR TITLE
Fixes

### LINKED ISSUE #236: Parametrized packs fail for arity <= 1
If you try to create a parametrized pack `‹i: n, i›` with arity `n <= 1` as shown in the example below, Thorin will run into the following assertion:
```
thorin: thorin/util/cast.h:23: T* thorin::RuntimeCast<B>::as() [with T = thorin::Arr; B = thorin::Def]: Assertion `isa<T>()' failed.
Aborted
```
#### Example
```rust
.let p1 = ‹i: 2; i›; // ok: (0, 1)
.let p2 = ‹i: 1; i›; // fail, should be: (0,) = 0
.let p3 = ‹i: 0; i›; // fail, should be: ()
```

### PR DESCRIPTION
**Pull request by leissa**
Various fixes and improvements
* fixed a weird edge case when checking alpha-equiv for mutables with same arity ...
* fixed #236
* new CLI switch `--break-on-alpha-unequal` which helps a lot to debug probls 
* some cleanup

### CODE REVIEW

File: thorin/check.h [hunk 1]
```diff
@@ -23,13 +23,15 @@ class Infer : public Def {
     Infer* unset() { return Def::unset()->as<Infer>(); }
     ///@}
 
-    /// @name union-find
-    ///@{
+    /// Eliminate Infer%s that have may have been resolved in the meantime by rebuilding.
```
Comment (NeuralCoder3) [inline thorin/check.h:26]: "Eliminate Infer%s that ~~have~~ may have been resolved in the meantime by rebuilding"

File: thorin/check.cpp [hunk 2]
```diff
@@ -42,16 +59,35 @@ const Def* Infer::find(const Def* def) {
...
+        }
+        return true;
+    }
+    return false;
+}
 /*
  * Check
  */
 
+#ifdef THORIN_ENABLE_CHECKS
```
Comment (NeuralCoder3) [inline thorin/check.cpp:78]: Isn't there missing a case to define `bool Check::fail` if `THORIN_ENABLE_CHECKS` isn't defined?

**Review by NeuralCoder3 — APPROVED** [review]

File: thorin/check.cpp (hunk 2 above)
Comment (leissa) [reply thorin/check.cpp:78]: This is inline in the header
